In [1]:
import pandas as pd
import convert as c

In [2]:
headers = ['date', 'player','item']

In [3]:
snapshot = pd.read_csv('csv/2021_01_21_loot_snapshot.csv')
snapshot['date'] = snapshot['date'].map(c.dt)

In [4]:
roster = pd.read_csv('csv/roster_with_class.csv')
roster

          player         rank    class
0        Puzzles  Core Raider    Druid
1         Sunorc         Mute   Hunter
2           Cyxn         Mute   Hunter
3         Sillac      Officer   Hunter
4          Stoff         Mute   Hunter
..           ...          ...      ...
145        Yurei       Raider   Priest
146  Cootertimer       Raider   Shaman
147          Bcm       Member   Priest
148  Toddmanflex       Raider  Warrior
149       Lexani        Trial  Warlock

[150 rows x 3 columns]

In [5]:
snapshot['item'] = snapshot['item'].apply(lambda x: str(x).split('(')[0])
snapshot

           player                     item       date
0         Puzzles        Ghoul Skin Tunic  2020-12-06
1        Matamata                T3 Boots  2020-12-22
2    Schmoopaloop               T3 Gloves  2020-12-16
3        Rangebot            T3 Shoulders  2020-12-03
4          Sillac                 T3 Belt  2020-12-17
..            ...                      ...        ...
202        Stango        Ghoul Skin Tunic  2021-01-20
203     Cleofatra        The Plague Bearer 2020-12-10
204  Nolimitation            T3 Shoulders  2020-12-10
205     Cleofatra                 T3 Legs  2020-12-10
206  Nolimitation  Gluth's Missing Collar  2020-12-10

[207 rows x 3 columns]

In [6]:
ss = snapshot.merge(roster, on='player', how='left').rename(columns={'item':'old_item_name'})
ss

           player            old_item_name       date         rank    class
0         Puzzles        Ghoul Skin Tunic  2020-12-06  Core Raider    Druid
1        Matamata                T3 Boots  2020-12-22  Core Raider    Druid
2    Schmoopaloop               T3 Gloves  2020-12-16  Core Raider    Druid
3        Rangebot            T3 Shoulders  2020-12-03  Core Raider   Hunter
4          Sillac                 T3 Belt  2020-12-17      Officer   Hunter
..            ...                      ...        ...          ...      ...
202        Stango        Ghoul Skin Tunic  2021-01-20  Core Raider  Warrior
203     Cleofatra        The Plague Bearer 2020-12-10      Officer  Warrior
204  Nolimitation            T3 Shoulders  2020-12-10      Officer  Warrior
205     Cleofatra                 T3 Legs  2020-12-10      Officer  Warrior
206  Nolimitation  Gluth's Missing Collar  2020-12-10      Officer  Warrior

[207 rows x 5 columns]

In [7]:
ss['player'] = ss['player'].map(c.deadshot)

In [8]:
ss.sort_values(by='date',inplace=True)

Map old item names to new item names

In [9]:
ss['item'] = ss.apply(c.convert, axis=1)

Filter out items older than 1/12/2021

In [10]:
cleaned_old_loot = ss[ss['date'] < pd.to_datetime('1/13/2021', format='%m/%d/%Y')]

In [11]:
cleaned_old_loot = cleaned_old_loot[headers]

In [12]:
cleaned_old_loot['item'] = cleaned_old_loot['item'].map(str.strip)
cleaned_old_loot[cleaned_old_loot['item'] == 'Ghoul Skin Tunic']

        date   player              item
0 2020-12-06  Puzzles  Ghoul Skin Tunic

In [13]:
cleaned_old_loot[headers].to_csv('csv/cleaned_old_loot.csv', index = False)
cleaned_old_loot[headers]

          date        player                           item
3   2020-12-03      Rangebot           Desecrated Spaulders
198 2020-12-03         Ziion        Desecrated Shoulderpads
5   2020-12-03      Deadshot            Band of Reanimation
87  2020-12-03         Kazuu        Desecrated Shoulderpads
16  2020-12-03        Groves              The End of Dreams
..         ...           ...                            ...
79  2021-01-07  Schmoopaloop        Ring of the Dreamwalker
195 2021-01-07       Therian           Desecrated Legguards
37  2021-01-07     Candykong             Shroud of Dominion
89  2021-01-07    Labignoune      Resilience of the Scourge
13  2021-01-07         Kazuu  Hammer of the Twisting Nether

[158 rows x 3 columns]